name: Build
on:
  pull_request
jobs:
  build:
    name: Building TestKit
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - name: Build SPM
      run: swift build
      