name: CocoaPodsRelease
on:
  workflow_run:
    workflows: ["Release"]
    branches: [master]
    types: 
      - completed
jobs:
  PodRelease:
    name: Update Podspec and publish
    runs-on: macos-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: pod repo update
        uses: wlixcc/pod-lib-update-action@1.0.0
        with:
          spec_repo_url: https://wlixcc:${{secrets.ACCESS_TOKEN}}@github.com/MathVasc/TestKit.git
          spec_file_path: /TestKit.podspec 