name: 'Update pob lib'
on: 
  create:
    tags: 
      - v*
jobs:
  pod_lib_update:
    runs-on: macos-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: pod lib update
        uses: wlixcc/pod-lib-update-action@1.0.0
        with:
          spec_repo_url: https://wlixcc:${{secrets.ACCESS_TOKEN}}@https://github.com/MathVasc/TestKit.git 
          spec_file_path: /TestKit.podspec