name: 'Update pob lib'
on:
  push:
    tags:
      - '*'
jobs:
  pod_lib_update:
    runs-on: macos-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: pod repo update
          uses: maxep/pod-repo-push-action@0.1.2
          with:
            repo-url: https://maxep:${{ secrets.ACCESS_TOKEN }}@github.com/MathVasc/TestKit.git 