name: Release
on:
  push:
    branches:
      - master
jobs:
  UpdateProject:
    name: Update TestKit Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - name: Setup for Carthage and CocoaPods
      run: |
        rm -rf TestKit.xcodeproj
        swift package generate-xcodeproj --xcconfig-overrides ./ios.xcconfig
        ./Scripts/UpdatePodspec.sh
    - name: Push project
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Release Carthage and CocoaPods"
        git push
  BumpVersion:
    name: Bump Version
    needs: UpdateProject
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
  PodRelease:
    name: Update Podspec and publish
    needs: BumpVersion
    runs-on: macos-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Pod repo update
        run: ./Scripts/PodPublish.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
