name: Release
on:
  push:
    paths-ignore:
      - 'TestKit.xcodeproj'
    branches:
      - master
jobs:
  UpdateProject:
    name: Update TestKit Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - name: Generate Project for Carthage
      run: |
        rm -rf TestKit.xcodeproj
        swift package generate-xcodeproj --xcconfig-overrides ./ios.xcconfig
    - name: Push project
      run: |
        git config --global user.name 'MathVasc'
        git config --global user.email 'ma.vasconcelos98@gmail.com'
        git add .
        git commit -m "Release: Update Project"
        git push origin master
  BumpVersion:
    name: Bump Version
    needs: UpdateProject
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        ref: master
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}